# Generated by Django 2.0 on 2018-08-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.TextField(max_length=36)),
                ('Agency', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialty', models.TextField(max_length=40)),
                ('Localisation', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='HajjParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birthday', models.DateTimeField()),
                ('Bloodtype', models.TextField(choices=[('A', 'A+'), ('B', 'B+'), ('O', 'O+'), ('AB', 'AB+'), ('A', 'A-'), ('B', 'B-'), ('O', 'O-'), ('AB', 'AB-')])),
            ],
        ),
        migrations.CreateModel(
            name='Ilness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Contageous', models.BooleanField()),
                ('Transfarabilty', models.TextField(choices=[('B', 'Blood'), ('A', 'AIR'), ('O', 'Other')])),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
