# Generated by Django 2.0.3 on 2018-04-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180419_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seuil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('p', 'ponctuelle'), ('a', 'annuelle'), ('h', 'hebdomadaire')], max_length=1)),
                ('seuil', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DateR',
        ),
    ]
