# Generated by Django 2.0.3 on 2018-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180428_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuil',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seuil',
            name='type',
            field=models.CharField(blank=True, choices=[('p', 'ponctuelle'), ('a', 'annuelle'), ('h', 'hebdomadaire')], max_length=1, null=True),
        ),
    ]
