# Generated by Django 2.0.3 on 2018-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180430_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuil',
            name='type',
            field=models.CharField(blank=True, choices=[('ponctuelle', 'ponctuelle'), ('annuelle', 'annuelle'), ('hebdomadaire', 'hebdomadaire')], max_length=1, null=True),
        ),
    ]
