# Generated by Django 2.0.3 on 2018-05-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180501_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuil',
            name='type',
            field=models.CharField(blank=True, choices=[('p', 'ponctuelle'), ('a', 'annuelle'), ('h', 'hebdomadaire')], max_length=1, null=True),
        ),
    ]
