# Generated by Django 2.0.3 on 2018-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180501_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuil',
            name='type',
            field=models.CharField(blank=True, choices=[('Ponctuelle', 'ponctuelle'), ('Annuelle', 'annuelle'), ('Hebdomadaire', 'hebdomadaire')], max_length=10, null=True),
        ),
    ]
