# Generated by Django 2.0.3 on 2018-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180501_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuil',
            name='seuil',
            field=models.IntegerField(null=True),
        ),
    ]
