# Generated by Django 2.0.4 on 2018-05-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20180503_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('adr', models.CharField(max_length=255)),
                ('adr_mail', models.EmailField(max_length=254)),
                ('num_telephone', models.CharField(max_length=11)),
                ('specialite', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='rendez_vous_externe',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Homme', 'homme'), ('Femme', 'femme')], max_length=5),
        ),
    ]
