# Generated by Django 2.0.4 on 2018-05-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180504_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adr_mail',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='num_telephone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='specialite',
            field=models.CharField(max_length=255),
        ),
    ]
