# Generated by Django 2.0.4 on 2018-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20180504_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
