# Generated by Django 2.0.4 on 2018-05-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20180504_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_patient', models.IntegerField()),
                ('date', models.DateField()),
                ('poids', models.IntegerField()),
                ('taille', models.IntegerField()),
                ('TA', models.CharField(max_length=25)),
                ('observation', models.CharField(max_length=255)),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_pere', models.CharField(max_length=25)),
                ('nom_mere', models.CharField(max_length=25)),
                ('prenom_mere', models.CharField(max_length=25)),
                ('endogamie', models.BooleanField()),
                ('num_telephpne', models.CharField(max_length=25)),
                ('adr_mail', models.EmailField(max_length=255)),
                ('RH_pere', models.CharField(max_length=25)),
                ('RH_mere', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='adr_mail_parent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='num_telephone_parent',
        ),
        migrations.AddField(
            model_name='patient',
            name='willaya',
            field=models.CharField(default='ff', max_length=255),
        ),
        migrations.AlterField(
            model_name='rendez_vous_externe',
            name='sexe',
            field=models.CharField(blank=True, choices=[('enfant', 'homme'), ('Femme', 'femme')], max_length=5),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Parents'),
        ),
    ]
