# Generated by Django 2.0.4 on 2018-06-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20180518_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_de_naissance_patient',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Parents'),
        ),
    ]
