# Generated by Django 2.0.4 on 2018-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20180604_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe_patient',
            field=models.CharField(max_length=25),
        ),
    ]
