# Generated by Django 2.0.4 on 2018-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20180604_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='num_telephpne',
        ),
        migrations.AddField(
            model_name='parents',
            name='num_telephone',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='RH_mere',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='RH_pere',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='adr_mail',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='nom_mere',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='prenom_mere',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='prenom_pere',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
