# Generated by Django 2.0.4 on 2018-06-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20180605_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Patient'),
        ),
    ]
