# Generated by Django 2.0.4 on 2018-06-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20180605_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='pic',
        ),
    ]
