# Generated by Django 2.0.4 on 2018-06-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_consultation_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Parents')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remb', models.CharField(max_length=10, null=True)),
                ('nom_commercial', models.CharField(max_length=200, null=True)),
                ('dci', models.CharField(max_length=200, null=True)),
                ('laboratoire', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=200, null=True)),
                ('forme', models.CharField(max_length=200, null=True)),
                ('dosage', models.CharField(max_length=200, null=True)),
                ('cond', models.CharField(max_length=200, null=True)),
                ('numero', models.IntegerField(null=True)),
            ],
        ),
    ]
