# Generated by Django 2.0.4 on 2018-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20180606_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous_externe',
            name='wilaya',
            field=models.CharField(choices=[('Choice1', '1 - Adrar'), ('Choice2', '2 - Chlef'), ('Choice3', '3 - Laghouat'), ('Choice4', '4 - Oum El Bouaghi'), ('Choice5', '5 - Batna'), ('Choice6', '6 - Béjaïa'), ('Choice7', '7 - Biskra'), ('Choice8', '8 - Béchar'), ('Choice9', '9 - Blida'), ('Choice10', '10 - Bouira'), ('Choice11', '11 - Tamanrasset'), ('Choice12', '12 - Tébessa'), ('Choice13', '13 - Tlemcen'), ('Choice14', '14 - Tiaret'), ('Choice15', '15 - Tizi Ouzou'), ('Choice16', '16 - Alger'), ('Choice17', '17 - Djelfa'), ('Choice18', '18 - Jijel'), ('Choice19', '19 - Sétif'), ('Choice20', '20 - Saïda'), ('Choice21', '21 - Skikda'), ('Choice22', '22 - Sidi Bel Abbès'), ('Choice23', '23 - Annaba'), ('Choice24', '24 - Guelma'), ('Choice25', '25 - Constantine'), ('Choice26', '26 - Médéa'), ('Choice27', '27 - Mostaganem'), ('Choice28', "28 - M'Sila"), ('Choice29', '29 - Mascara'), ('Choice30', '30 - Ouargla'), ('Choice31', '31 - Oran'), ('Choice32', '32 - El Bayadh'), ('Choice33', '33 - Illizi'), ('Choice34', '34 - Bordj Bou Arreridj'), ('Choice35', '35 - Boumerdès'), ('Choice36', '36 - El Tarf'), ('Choice37', '37 - Tindouf'), ('Choice38', '38 - Tissemsilt'), ('Choice39', '39 - El Oued'), ('Choice40', '40 - Khenchela'), ('Choice41', '41 - Souk Ahras'), ('Choice42', '42 - Tipaza'), ('Choice43', '43 - Mila'), ('Choice44', '44 - Aïn Defla'), ('Choice45', '45 - Naâma'), ('Choice46', '46 - Aïn Témouchent'), ('Choice47', '47 - Ghardaïa'), ('Choice48', '48 - Relizane')], default=None, max_length=255, null=True),
        ),
    ]
