# Generated by Django 2.0.4 on 2018-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20180606_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierparents',
            name='nombre_cesariennes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dossierparents',
            name='nombre_gestations_mere',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dossierparents',
            name='nombre_parite_mere',
            field=models.IntegerField(default=0),
        ),
    ]
