# Generated by Django 2.0.4 on 2018-06-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20180608_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examan',
            old_name='glycémie_a_jeun',
            new_name='glycemie_a_jeun',
        ),
        migrations.RenameField(
            model_name='examan',
            old_name='phosphorémie',
            new_name='phosphoremie',
        ),
    ]
