# Generated by Django 2.0.4 on 2018-06-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20180608_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuil',
            name='rest',
            field=models.IntegerField(null=True),
        ),
    ]
