# Generated by Django 2.0.4 on 2018-06-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_seuil_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seuil',
            name='rest',
        ),
    ]
