# Generated by Django 2.0.4 on 2018-06-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_remove_seuil_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous_externe',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Fille', 'fille'), ('Garçon', 'garçon'), ('Non sexe déterminé', 'non_sexe_determiné')], max_length=250),
        ),
    ]
